import './app.scss'
import LayoutSidenav from "./layoutSidenav"
import LayoutFooter from "./layoutFooter"
import LayoutHeader from "./layoutHeader"
import AuthorizedPage from '../components/authorizedPage'
import { ToastContainer } from '../components/toastMessage'

export const metadata = {
  title: 'Victory - Admin Portal',
  description: 'Generated by Next.js',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <AuthorizedPage>
          <div className="dashboard-container">
            <div className="grid">
              <LayoutHeader />
              <LayoutSidenav />
              <main className="main">
                <AuthorizedPage>
                  {children}
                </AuthorizedPage>
              </main>
              <LayoutFooter /> 
            </div>
          </div>
        </AuthorizedPage>
        <ToastContainer />
      </body>
    </html>
  )
}
